sudo: 'required'

services:
  - docker

# Build and test the images (if this step fails the whole Travis build is considered a failure).
script:

  # Build Docker image
  # Create a docker image tag out of branch-name where / is replaced by -
  - cd webserver
  - tag="${TRAVIS_BRANCH/\//-}"
  - docker build -t pharmbio/imagedb-web:$tag .

  # Test container
    docker run pharmbio/imagedb-web:$tag python3 --version

after_success:
  # Login and push image
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push pharmbio/imagedb-web:$tag
