version: "2.4"

networks:
  image-db-net:
    external:
      name: image-db-net

volumes:
  # this is microimages r-o share
  mikroimages-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_MIKRO?You need to specify env SHARE_MIKRO, e.g. SHARE_MIKRO=/share/mikro}
      o: bind
  # this is thumbnail volume
  imagedb-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_IMAGEDB?You need to specify env SHARE_IMAGEDB, e.g. SHARE_IMAGEDB=/share/imagedb}
      o: bind
  # approot
  approot-bind:
    driver: local
    driver_opts:
      type: none
      device: ${APPROOT?You need to specify env APPROOT, e.g. APPROOT=/home/anders/pharmbio/imageDB/}
      o: bind

services:
  image-db-cli:
    image: pharmbio/imagedb-cli
    restart: always
    container_name: imagedb-cli
    command: python3 image-monitor.py
    cpus: 2
    mem_limit: 2g
    environment:
      # CONF_FILE: settings_dev_local.json
      CONF_FILE: ${CONF_FILE?You need to specify env CONF_FILE, e.g. settings_dev_local.json, settings_prod.json}
      DB_USER: postgres
      DB_PASS: example
      DB_PORT: 5432
    volumes:
      - mikroimages-bind:/share/mikro
      - imagedb-bind:/share/imagedb
      - approot-bind:/app
    networks:
      - image-db-net
