version: "2.4"

networks:
  image-db-net:
    external:
      name: image-db-net
  traefik:
    external:
      name: traefik_web

volumes:
  # this is microimages r-o share
  mikroimages-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_MIKRO?You need to specify env SHARE_MIKRO, e.g. SHARE_MIKRO=/share/mikro}
      o: bind
  # this is microimages r-o share
  externalimages-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_EXTERNAL?You need to specify env SHARE_EXTERNAL, e.g. SHARE_EXTERNAL=/share/data/external-datasets}
      o: bind
  # this is thumbnail volume
  imagedb-bind:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_IMAGEDB?You need to specify env SHARE_IMAGEDB, e.g. SHARE_IMAGEDB=/share/imagedb}
      o: bind

# Webroot
  imgagedb-webroot-bind:
    driver: local
    driver_opts:
      type: none
      device: ${WEBROOT?You need to specify env WEBROOT, e.g. WEBROOT=/home/anders/projekt/imagedb/webserver}
      o: bind

services:
  imagedbweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imageweb
    environment:
      CONF_FILE: ${CONF_FILE?You need to specify env CONF_FILE, e.g. settings_dev_local.json, settings_prod.json}
    cpus: 2
    mem_limit: 2g
    ports:
      - 8092:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=8092"
      - "traefik.http.routers.imagedbweb.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.imagedbweb.entrypoints=websecure"
      - "traefik.http.routers.imagedbweb.tls.certresolver=myresolver"
      # - traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH? You need to specify env TRAEFIK_BASIC_AUTH, e.g. TRAEFIK_BASIC_AUTH=username:$blablsbskjfhbsjhslkfsjlkdslkjf/kljsd}


    networks:
      - image-db-net
      - traefik
    volumes:
      - imgagedb-webroot-bind:/app
      - mikroimages-bind:/share/mikro
      - imagedb-bind:/share/imagedb
      - externalimages-bind:/share/data/external-datasets

