version: "2.4"

networks:
  image-db-net:
    driver: bridge
    name: image-db-net

volumes:
  # Either use a docker-volume for database
  #db-data-pg:
  
  # Or bind mount a directory
  db-data-pg:
    driver: local
    driver_opts:
      type: none
      device: ${SHARE_DB_DATA?You need to specify env SHARE_DB_DATA, e.g. SHARE_DB_DATA=/mnt/db_data}
      o: bind

services:

  imagedb:
    image: postgres:11.5
    restart: always
    cpus: 4
    mem_limit: 8g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - image-db-net

  adminer:
    image: adminer
    restart: always
    cpus: 2
    mem_limit: 2g
    ports:
      - 8088:8080
    networks:
      - image-db-net

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:0.11.3
    ports:
      - "8081:8081"
    networks:
      - image-db-net
    #links:
    #  - postgres:postgres  # my database container is called postgres, not db
    #environment:
    #  - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
