version: "3.5"

networks:
  image-db-net:
    driver: bridge
    name: image-db-net

volumes:
  db-data-pg:

services:

  imagedb:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - image-db-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - image-db-net
