version: "3.5"

networks:
  image-db-net:
    driver: bridge
    name: image-db-net

volumes:
  db-data-pg:

services:

  db:
    image: postgres:11.5
    restart: always
    container_name: image-pg
    environment:
      POSTGRES_USER: imagedb
      POSTGRES_PASSWORD: example
    volumes:
      - db-data-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
